feat: ✨ Browser attributes span processor (but also so much more)
honeycombio/honeycomb-opentelemetry-web pull request #45
Opened 2024-01-26 19:03 UTC by pkanal

## Which problem is this PR solving?
This PR adds the `BrowserAttributesSpanProcessor` which adds rich browser attributes to every span. Attributes like the page location and screen height and width might change during the lifecycle of a session so they are better captured through a Span Processor rather than on the Resource.

- Closes #11 

## Short description of the changes
- `BrowserAttributesSpanProcessor` class that adds attributes to each span
- `CompositeSpanProcessor` class that combines multiple span processors together since the base SDK does not support multiple span processors
- Span processor builder that configures the `BatchSpanProcessor` with the exporter as well as the `BrowserAttributesSpanProcessor` and an optional user provided span processor
- Had to switch the exporter being configured through this span processor builder since the base SDK does not support configuring an exporter through the `traceExporter` option if a `spanProcessor` is provided.

## How to verify that this has the expected result
- Run the test app and check for the additional browser attributes
- The data should still be exported to Honeycomb

2024-01-29 22:37 UTC, JamieDanielson reviewed
Main suggestion is regarding properties being used for width and height... otherwise on the whole this looks great!

2024-01-29 22:39 UTC, JamieDanielson requested changes
Setting as Request Changes for the browser width/height suggestion

2024-01-30 15:03 UTC, ahrbnsn approved these changes

2024-01-30 22:44 UTC, JamieDanielson approved these changes
This is so great! We may have some more readme updates but I'm fine doing that as a follow-up too

2024-01-31 15:02 UTC, merged